# Generated by Django 4.2.1 on 2023-05-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_musics_music_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musics',
            name='music_file',
            field=models.FileField(upload_to='media/', verbose_name='file'),
        ),
    ]
